In [1]:
import pandas as pd 

df = pd.read_csv("../data/raw/yelp_restaurant_reviews.csv")

In [2]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19896 entries, 0 to 19895
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Yelp URL     19896 non-null  str
 1   Rating       19896 non-null  int64
 2   Date         19896 non-null  str
 3   Review Text  19896 non-null  str
dtypes: int64(1), str(3)
memory usage: 621.9 KB

In [3]:
len(df)

19896

In [4]:
df['Date'] = pd.to_datetime(df['Date'])

In [5]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19896 entries, 0 to 19895
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Yelp URL     19896 non-null  str
 1   Rating       19896 non-null  int64
 2   Date         19896 non-null  datetime64[us]
 3   Review Text  19896 non-null  str
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 621.9 KB

In [6]:
df.isnull().sum()

Yelp URL       0
Rating         0
Date           0
Review Text    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["Review Text"].str.strip().eq("").sum()

np.int64(0)

In [9]:
df["Date"].min()

Timestamp('2005-06-24 00:00:00')

In [10]:
df["Date"].max()

Timestamp('2022-08-02 00:00:00')

In [11]:
df["Rating"].value_counts().sort_index()

Rating
1     1217
2     1280
3     2069
4     4447
5    10883
Name: count, dtype: int64

In [12]:
df["Yelp URL"].nunique()

49

In [13]:
df["Review Text"].str.len().mean()

np.float64(493.933353437877)

In [14]:
df["Review Text"].str.len().max()

np.int64(5990)

In [15]:
url_mas_repetida = df["Yelp URL"].mode()[0]

In [16]:


df[df["Yelp URL"] == url_mas_repetida]["Rating"].mean()

np.float64(4.07590597453477)

In [17]:
agrupados_por_restaurante = df.groupby("Yelp URL") #agrupo por restaurante
rating_promedio = agrupados_por_restaurante["Rating"].mean() #Agregacion para calcular el rating promedio
cantidad_reviews = agrupados_por_restaurante["Review Text"].count() #Agregacion para calcular la cantidad de reviews
#Creo un nuevo dataframe que resume las agregaciones creadas
restaurantes_info = pd.DataFrame({
    "cant_reviews": cantidad_reviews,
    "rating_promedio": rating_promedio
})

In [18]:
#Me quedo con los que tengan al menos 50 reviews
restaurantes_info = restaurantes_info[restaurantes_info["cant_reviews"] >= 50]
#Ordeno los restaurantes por rating promedio de mayor a menor
restaurantes_info =restaurantes_info.sort_values("rating_promedio", ascending=False)

In [19]:
restaurantes_info.head(1)

,cant_reviews,rating_promedio
Yelp URL,,
https://www.yelp.com/biz/novel-ice-cream-phoenix,1016,4.929134

In [20]:
restaurantes_info.sort_values("cant_reviews", ascending=False).head(1)

,cant_reviews,rating_promedio
Yelp URL,,
https://www.yelp.com/biz/am%C3%A9lies-french-bakery-and-caf%C3%A9-charlotte-11,2042,4.075906

In [21]:
restaurantes_info.head(5)

,cant_reviews,rating_promedio
Yelp URL,,
https://www.yelp.com/biz/novel-ice-cream-phoenix,1016,4.929134
https://www.yelp.com/biz/the-vegan-doughnut-company-lakewood-3,99,4.797980
https://www.yelp.com/biz/the-batchmaker-charlotte,102,4.794118
https://www.yelp.com/biz/mitchells-homemade-ice-cream-cleveland-cleveland-2,548,4.788321
https://www.yelp.com/biz/scooptopia-phoenix,188,4.760638

In [22]:
ordenados_por_peor_rating = restaurantes_info.sort_values("rating_promedio", ascending=True)
ordenados_por_peor_rating.head(5)

,cant_reviews,rating_promedio
Yelp URL,,
https://www.yelp.com/biz/carlos-bakery-las-vegas-3,1290,2.979845
https://www.yelp.com/biz/caff%C3%A9-bene-urbana-3,71,3.112676
https://www.yelp.com/biz/cr%C3%AApes-de-luxe-cleveland-2,85,3.388235
https://www.yelp.com/biz/milk-bar-las-vegas-las-vegas-3,1333,3.450113
https://www.yelp.com/biz/sloans-grand-canal-shoppes-las-vegas,159,3.666667